version: '3.4'

services:
  productvdb:
    container_name: productvdb
    restart: always
    ports:
        - "6379:6379" 

  ecommerce.api:
    container_name: ecommerce.api
    restart: always
    ports:
        - 8054:80
    depends_on:
        - productvdb